import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <div className='flex p-4 bg-blue-100 justify-between'>
          <div className="text-3xl font-bold text-gray-700">Friend Tech Club Tool</div>
          <ConnectButton />
        </div>
        <div className="p-8">
          <div className='flex items-center mb-4'>
            <div className='w-20 mr-2'>Token ID:</div>
            <input type="number" placeholder="Token ID" className="border border-gray-300 rounded-md px-4 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500" />
          </div>
          <div className='flex items-center mb-4'>
            <div className='w-20 mr-2'>Amount:</div>
            <input type="number" placeholder="Amount" className="border border-gray-300 rounded-md px-4 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500" />
          </div>
          <div className='flex'>
            <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mr-4">
              Buy
            </button>
            <button className="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">
              Sell
            </button>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  );
};

export default Home;
